services:
  backend:
    build: ./back-end
    container_name: soda-backend
    volumes:
      - soda_db:/app/data  
    ports:
      - "8000:8000"
    environment:
      - LLM_MODEL=MODEL_OF_YOUR_CHOICE
      - OPENAI_API_KEY=YOUR_API_KEY
      - BACKEND_BASE_URL=http://backend:8000
  frontend:
    build: ./frontend
    container_name: soda-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000

volumes:
  soda_db: